# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/jirate_database_development
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test_vm
  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: jirate_database_development
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge