# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src/
  server:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test_vm
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jirateuser
      POSTGRES_PASSWORD: jiratepassword
      POSTGRES_DB: jirate_database_development
    ports:
      - 5432:5432
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge
