# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src/
  server:
    environment:
      DATABASE_URL: postgresql://jirateuser:jiratepassword@db:5432/jirate_database_development
      NODE_ENV: development
    restart: always
    build: .
    ports:
      - 5000:5000
    command: yarn dev
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jirateuser
      POSTGRES_PASSWORD: jiratepassword
      POSTGRES_DB: jirate_database_development
    ports:
      - 5432:5432