version: '3'
services:
  mock-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
  test-api:
    build: .
    command: yarn test
    depends_on:
      - mock-db
    tty: true
    env_file:
      - .env.test
