# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    image: jiratedev/server
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    environment:
      DATABASE_URL: postgresql://jirateuser:jiratepassword@db:5432/jirate_database_development
      NODE_ENV: production
    depends_on:
      - db
  client:
    # build: ./client
    image: jiratedev/client
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      NODE_ENV: production
  db:
    image: postgres
    environment:
      POSTGRES_USER: jirateuser
      POSTGRES_PASSWORD: jiratepassword
      POSTGRES_DB: jirate_database_development
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build: