name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run tests
        run:
          yarn prisma db push
          yarn jest
        env:
          DATABASE_URL: postgresql://ciUser:ciPassword@localhost:5432/test
