name: CI
on: push
jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    services:
      client:
        build: ./client
        ports:
          - 3000:3000
        volumes:
          - ./client/src:/app/src/
      server:
        build: .
        command: sh -c "npm run build && npm run start"
        expose:
          - 5001
        environment:
          DATABASE_URL: postgresql://ciUser:ciPassword@db:5432/jirate_database_test
          NODE_ENV: production
          PORT: 5001
          JWT_SECRET: AQQDjPVlnj5Et0D3DKR4uxDUqq5WqMaofa1lHv2kDsA0
        depends_on:
          - db
        volumes:
          - ./:/app
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: ciUser
          POSTGRES_PASSWORD: ciPassword
          POSTGRES_DB: jirate_database_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Integration testing
      run: |
        yarn prisma migrate dev
        yarn test
      env:
        DATABASE_URL: postgresql://ciUser:ciPassword@localhost:5432/test
    - name: Cypress run
      uses: cypress-io/github-action@v2